events {}

http {
    server {
        listen 80;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "This is a temporary cert issuance server";
        }
    }
}