events {}

http {
    server {
        listen 80;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "This is a http server for certificate renewal";
        }
    }

    server {
        listen 443 ssl;
        server_name blockchain.rise;

        ssl_certificate /etc/letsencrypt/live/blockchain.rise/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/blockchain.rise/privkey.pem;



        location / {
            proxy_pass http://blockchain:5000;
        }
    }

    server {
        listen 443 ssl;
        server_name raahguu.nya;

        ssl_certificate /etc/letsencrypt/live/blockchain.rise/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/blockchain.rise/privkey.pem;

        location / {
            return 200 "Yay!";
        }
    }

    server {
        listen 443 ssl;
        server_name lounge.uwu;

        ssl_certificate /etc/letsencrypt/live/blockchain.rise/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/blockchain.rise/privkey.pem;

        location / {
            proxy_pass http://lounge:80;
        }
    }
}